import React, { useState } from 'react';
import { SectionHeader } from '../../components/domain/SectionHeader';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { ExplanationDrawer } from './ExplanationDrawer';
import type { Explanation } from '../../types/api';
import { ShieldCheck, Search } from 'lucide-react';

const SAMPLE_EXPLANATIONS: Explanation[] = [
  {
    explanation_id: "EXP-BLK-01",
    entity_type: "BLOCK",
    entity_id: "BLK-NDLS-01",
    summary: "Maintenance block scheduled during nocturnal freight corridor lull (23:00 - 01:30) to minimize passenger disruption while co-locating TRD cantilever and ENG rail defect repairs.",
    reason_codes: ["NOCTURNAL_INTERVAL_OPTIMAL", "SHADOW_BLOCK_COMPATIBLE", "CREW_CONCURRENCY_OK"],
    evidence: {
      passenger_train_conflicts: 0,
      freight_diversion_penalty_minutes: 12,
      saved_possession_minutes: 95,
      department_overlap_ratio: 0.85
    },
    deterministic_inputs: {
      section: "NDLS-AGC (Km 45.0 - 46.5)",
      primary_task: "TSK-ENG-NDLS-045-01",
      secondary_task: "TSK-TRD-NDLS-046-02",
      power_shutdown_required: true
    },
    generated_by: "AI_EXPLAINABILITY_ENGINE_V1"
  },
  {
    explanation_id: "EXP-GRP-02",
    entity_type: "GROUPING",
    entity_id: "SB-NDLS-301",
    summary: "TRD maintenance combined into engineering possession window because both activities require track isolation within 1.5 km and TRD team is certified for concurrent track work.",
    reason_codes: ["SPATIAL_PROXIMITY_UNDER_2KM", "OHE_SHUTDOWN_SHARED", "SAFETY_CLEARANCE_VALID"],
    evidence: {
      spatial_distance_km: 0.2,
      power_shutdown_shared: true,
      corridor_occupancy_savings: "38%"
    },
    deterministic_inputs: {
      location_start_km: 45.0,
      location_end_km: 46.5,
      participating_departments: ["ENG", "TRD"]
    },
    generated_by: "SHADOW_BLOCK_OPTIMIZER"
  },
  {
    explanation_id: "EXP-REJ-03",
    entity_type: "REJECTION",
    entity_id: "TSK-SNT-NDLS-099",
    summary: "Signal relay replacement rejected from Block BLK-NDLS-01 due to insufficient headway with Gatimaan Express passage scheduled at 02:05.",
    reason_codes: ["HEADWAY_VIOLATION", "BUFFER_BELOW_MINIMUM", "PASSENGER_TRAIN_HIGH_PRIORITY"],
    evidence: {
      required_buffer_minutes: 30,
      available_buffer_minutes: 14,
      priority_train: "12050 Gatimaan Exp"
    },
    deterministic_inputs: {
      conflict_km: 45.2,
      train_speed_kmh: 160
    },
    generated_by: "COMPATIBILITY_CHECKER"
  }
];

export const ExplainPage: React.FC = () => {
  const [selectedExplanation, setSelectedExplanation] = useState<Explanation | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);

  const handleInspect = (explanation: Explanation) => {
    setSelectedExplanation(explanation);
    setDrawerOpen(true);
  };

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Decision Explainability & Proof Traces"
        description="Audit-ready deterministic proof traces, constraint validation reasons, and AI optimization rationales."
        badge={
          <span className="badge badge-optimal font-mono text-xs flex items-center gap-1">
            <ShieldCheck size={14} />
            AUDIT PROOF ATTACHED
          </span>
        }
      />

      <div className="grid grid-cols-1 gap-4">
        {SAMPLE_EXPLANATIONS.map((exp) => (
          <Card
            key={exp.explanation_id}
            title={`${exp.entity_type} // ${exp.entity_id}`}
            subtitle={`Trace ID: ${exp.explanation_id} · Generated By: ${exp.generated_by}`}
            actions={
              <Button
                variant="primary"
                size="sm"
                icon={<Search size={14} />}
                onClick={() => handleInspect(exp)}
              >
                Inspect Proof Trace
              </Button>
            }
          >
            <p className="text-sm font-mono text-text-primary mb-3">
              {exp.summary}
            </p>
            <div className="flex flex-wrap gap-2">
              {exp.reason_codes.map((code) => (
                <span
                  key={code}
                  className="bg-background-main border-2 border-surface-border px-2 py-0.5 font-mono text-xs text-status-optimal"
                >
                  {code}
                </span>
              ))}
            </div>
          </Card>
        ))}
      </div>

      <ExplanationDrawer
        explanation={selectedExplanation}
        isOpen={drawerOpen}
        onClose={() => setDrawerOpen(false)}
      />
    </div>
  );
};

export default ExplainPage;
