import React, { useEffect, useState } from 'react';
import { SectionHeader } from '../../components/domain/SectionHeader';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { ExplanationDrawer } from './ExplanationDrawer';
import { getExplanations } from '../../api/client';
import type { Explanation } from '../../types/api';
import { ShieldCheck, Search, Loader2 } from 'lucide-react';

const ENTITY_TYPE_COLORS: Record<string, string> = {
  BLOCK: 'text-[#10B981] border-[#10B981]/30 bg-[#10B981]/10 shadow-[0_0_8px_rgba(16,185,129,0.2)]',
  GROUPING: 'text-[#8B5CF6] border-[#8B5CF6]/30 bg-[#8B5CF6]/10 shadow-[0_0_8px_rgba(139,92,246,0.2)]',
  REJECTION: 'text-[#EF4444] border-[#EF4444]/30 bg-[#EF4444]/10 shadow-[0_0_8px_rgba(239,68,68,0.2)]',
  TASK: 'text-[#10B981] border-[#10B981]/30 bg-[#10B981]/10 shadow-[0_0_8px_rgba(16,185,129,0.2)]',
  WINDOW: 'text-[#F59E0B] border-[#F59E0B]/30 bg-[#F59E0B]/10 shadow-[0_0_8px_rgba(245,158,11,0.2)]',
  SCHEDULE: 'text-[#06B6D4] border-[#06B6D4]/30 bg-[#06B6D4]/10 shadow-[0_0_8px_rgba(6,182,212,0.2)]',
};

export const ExplainPage: React.FC = () => {
  const [explanations, setExplanations] = useState<Explanation[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedExplanation, setSelectedExplanation] = useState<Explanation | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);

  useEffect(() => {
    getExplanations()
      .then((res) => {
        if (res.success) setExplanations(res.data);
      })
      .finally(() => setLoading(false));
  }, []);

  const handleInspect = (explanation: Explanation) => {
    setSelectedExplanation(explanation);
    setDrawerOpen(true);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64 border border-white/5 border-dashed rounded-xl bg-black/20">
        <div className="font-mono text-[#06B6D4] flex items-center gap-2 tracking-widest text-[10px] uppercase font-bold">
          <Loader2 size={16} className="animate-spin" />
          LOADING EXPLANATION TRACES...
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Decision Explainability & Proof Traces"
        description="Audit-ready deterministic proof traces, constraint validation reasons, and AI optimization rationales."
        badge={
          <span className="bg-[#10B981]/10 text-[#10B981] border border-[#10B981]/30 px-2 py-1 rounded font-mono text-[10px] uppercase tracking-widest shadow-[0_0_10px_rgba(16,185,129,0.2)] flex items-center gap-1">
            <ShieldCheck size={14} />
            AUDIT PROOF ATTACHED
          </span>
        }
      />

      <div className="grid grid-cols-1 gap-4">
        {explanations.map((exp) => {
          const typeStyle = ENTITY_TYPE_COLORS[exp.entity_type] ?? 'text-gray-400 border-white/10 bg-black/40';

          return (
            <Card
              key={exp.explanation_id}
              title={
                <div className="flex items-center gap-3">
                  <span className={`px-2 py-1 text-[9px] font-bold uppercase border rounded tracking-widest ${typeStyle}`}>
                    {exp.entity_type}
                  </span>
                  <span className="font-mono text-white tracking-widest text-sm">{exp.entity_id}</span>
                </div>
              }
              subtitle={`Trace ID: ${exp.explanation_id} · Generated By: ${exp.generated_by}`}
              actions={
                <Button
                  variant="primary"
                  size="sm"
                  icon={<Search size={14} />}
                  onClick={() => handleInspect(exp)}
                  className="tracking-widest text-[10px] uppercase"
                >
                  Inspect Proof Trace
                </Button>
              }
            >
              <p className="text-xs font-mono text-gray-300 mb-4 leading-relaxed bg-black/20 p-3 rounded-lg border border-white/5">
                {exp.summary}
              </p>
              <div className="flex flex-wrap gap-2">
                {exp.reason_codes.map((code) => (
                  <span
                    key={code}
                    className="bg-black/50 border border-white/10 rounded px-2 py-1 font-mono text-[10px] text-[#10B981] font-bold tracking-widest shadow-[0_0_8px_rgba(16,185,129,0.1)]"
                  >
                    {code}
                  </span>
                ))}
              </div>
            </Card>
          );
        })}
      </div>

      <ExplanationDrawer
        explanation={selectedExplanation}
        isOpen={drawerOpen}
        onClose={() => setDrawerOpen(false)}
      />
    </div>
  );
};

export default ExplainPage;
