import React, { useState } from 'react';
import { Drawer } from '../../components/common/Drawer';
import { Badge } from '../../components/common/Badge';
import { Button } from '../../components/common/Button';
import { ShieldCheck, ChevronDown, ChevronUp, Copy, Terminal } from 'lucide-react';
import type { Explanation } from '../../types/api';

interface Props {
  explanation: Explanation | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ExplanationDrawer: React.FC<Props> = ({ explanation, isOpen, onClose }) => {
  const [showInputs, setShowInputs] = useState(false);
  const [copied, setCopied] = useState(false);

  if (!explanation) return null;

  const handleCopyJson = () => {
    navigator.clipboard.writeText(JSON.stringify(explanation, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  return (
    <Drawer
      isOpen={isOpen}
      onClose={onClose}
      title={
        <div className="flex items-center gap-2">
          <Terminal size={16} className="text-accent-400" />
          <span>Audit: {explanation.entity_id}</span>
        </div>
      }
      subtitle={`GENERATED BY: ${explanation.generated_by} // TYPE: ${explanation.entity_type}`}
      footer={
        <div className="flex items-center justify-between gap-3">
          <Button
            variant="secondary"
            size="sm"
            icon={<Copy size={13} />}
            onClick={handleCopyJson}
          >
            {copied ? 'Copied JSON!' : 'Copy Audit JSON'}
          </Button>
          <Button variant="primary" size="sm" onClick={onClose}>
            Close Inspector
          </Button>
        </div>
      }
    >
      <div className="space-y-5 font-mono">
        {/* Deterministic Verification Badge */}
        <div className="p-3 bg-status-feasible-bg border border-status-feasible/30 rounded-sm flex items-center justify-between">
          <div className="flex items-center gap-2 text-status-feasible">
            <ShieldCheck size={16} />
            <span className="text-micro uppercase font-semibold tracking-wider">
              Deterministic Math / Rule Provenance
            </span>
          </div>
          <span className="text-[10px] text-content-tertiary">
            NON-STOCHASTIC
          </span>
        </div>

        {/* Narrative Summary */}
        <div className="p-4 bg-surface border border-border-hairline rounded-sm space-y-2">
          <span className="text-micro text-content-tertiary uppercase block">
            Mathematical Decision Summary
          </span>
          <p className="text-small text-content-primary font-sans leading-relaxed">
            {explanation.summary}
          </p>
        </div>

        {/* Reason Codes as Chips Row */}
        <div>
          <h4 className="text-micro uppercase tracking-wider text-content-tertiary mb-2 pb-1 border-b border-border-hairline">
            Rule & Constraint Codes ({explanation.reason_codes.length})
          </h4>
          <div className="flex flex-wrap gap-1.5">
            {explanation.reason_codes.map((code) => (
              <span
                key={code}
                className="px-2 py-1 rounded-sm bg-surface-sunken border border-border-hairline text-micro font-semibold text-accent-400"
              >
                {code}
              </span>
            ))}
          </div>
        </div>

        {/* Formatted Evidence Key-Value Inspector */}
        <div>
          <h4 className="text-micro uppercase tracking-wider text-content-tertiary mb-2 pb-1 border-b border-border-hairline">
            Quantitative Evidence Metrics
          </h4>
          <div className="p-3 bg-surface-sunken border border-border-hairline rounded-sm overflow-x-auto custom-scrollbar text-small">
            {explanation.evidence && typeof explanation.evidence === 'object' ? (
              <div className="space-y-1.5">
                {Object.entries(explanation.evidence).map(([key, value]) => (
                  <div key={key} className="flex items-start justify-between gap-4 py-1 border-b border-border-subtle/40 last:border-0">
                    <span className="text-content-tertiary text-micro uppercase">{key}:</span>
                    <span className="text-content-primary font-semibold text-micro tabular-nums text-right">
                      {typeof value === 'object' ? JSON.stringify(value) : String(value)}
                    </span>
                  </div>
                ))}
              </div>
            ) : (
              <pre className="text-micro text-content-secondary">{String(explanation.evidence)}</pre>
            )}
          </div>
        </div>

        {/* Deterministic Inputs (Collapsible Section) */}
        <div>
          <button
            onClick={() => setShowInputs(!showInputs)}
            className="w-full flex items-center justify-between py-2 text-micro uppercase tracking-wider text-content-tertiary hover:text-content-primary border-b border-border-hairline cursor-pointer"
          >
            <span>Raw Deterministic Input Parameters</span>
            {showInputs ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
          </button>

          {showInputs && (
            <div className="mt-2 p-3 bg-surface-sunken border border-border-hairline rounded-sm overflow-x-auto custom-scrollbar">
              <pre className="text-micro text-content-secondary leading-relaxed">
                {JSON.stringify(explanation.deterministic_inputs, null, 2)}
              </pre>
            </div>
          )}
        </div>
      </div>
    </Drawer>
  );
};

export default ExplanationDrawer;
