import React, { useEffect, useState } from 'react';
import { SectionHeader } from '../../components/domain/SectionHeader';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';
import { ExplanationDrawer } from './ExplanationDrawer';
import { getExplanations } from '../../api/client';
import type { Explanation } from '../../types/api';
import { ShieldCheck, Search, Loader2 } from 'lucide-react';

const ENTITY_TYPE_COLORS: Record<string, string> = {
  BLOCK: 'text-status-feasible border-status-feasible bg-status-feasible/10',
  GROUPING: 'text-status-shadow border-status-shadow bg-status-shadow/10',
  REJECTION: 'text-status-critical border-status-critical bg-status-critical/10',
  TASK: 'text-status-optimal border-status-optimal bg-status-optimal/10',
  WINDOW: 'text-status-warning border-status-warning bg-status-warning/10',
  SCHEDULE: 'text-text-cyan border-text-cyan bg-text-cyan/10',
};

export const ExplainPage: React.FC = () => {
  const [explanations, setExplanations] = useState<Explanation[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedExplanation, setSelectedExplanation] = useState<Explanation | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);

  useEffect(() => {
    getExplanations()
      .then((res) => {
        if (res.success) setExplanations(res.data);
      })
      .finally(() => setLoading(false));
  }, []);

  const handleInspect = (explanation: Explanation) => {
    setSelectedExplanation(explanation);
    setDrawerOpen(true);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="font-mono text-text-muted flex items-center gap-2">
          <Loader2 size={16} className="animate-spin" />
          LOADING EXPLANATION TRACES...
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <SectionHeader
        title="Decision Explainability & Proof Traces"
        description="Audit-ready deterministic proof traces, constraint validation reasons, and AI optimization rationales."
        badge={
          <span className="badge badge-optimal font-mono text-xs flex items-center gap-1">
            <ShieldCheck size={14} />
            AUDIT PROOF ATTACHED
          </span>
        }
      />

      <div className="grid grid-cols-1 gap-4">
        {explanations.map((exp) => {
          const typeStyle = ENTITY_TYPE_COLORS[exp.entity_type] ?? 'text-text-muted border-surface-border bg-background-main';

          return (
            <Card
              key={exp.explanation_id}
              title={
                <div className="flex items-center gap-3">
                  <span className={`px-1.5 py-0.5 text-[10px] font-bold uppercase border ${typeStyle}`}>
                    {exp.entity_type}
                  </span>
                  <span>{exp.entity_id}</span>
                </div>
              }
              subtitle={`Trace ID: ${exp.explanation_id} · Generated By: ${exp.generated_by}`}
              actions={
                <Button
                  variant="primary"
                  size="sm"
                  icon={<Search size={14} />}
                  onClick={() => handleInspect(exp)}
                >
                  Inspect Proof Trace
                </Button>
              }
            >
              <p className="text-sm font-mono text-text-primary mb-3">
                {exp.summary}
              </p>
              <div className="flex flex-wrap gap-2">
                {exp.reason_codes.map((code) => (
                  <span
                    key={code}
                    className="bg-background-main border-2 border-surface-border px-2 py-0.5 font-mono text-xs text-status-optimal"
                  >
                    {code}
                  </span>
                ))}
              </div>
            </Card>
          );
        })}
      </div>

      <ExplanationDrawer
        explanation={selectedExplanation}
        isOpen={drawerOpen}
        onClose={() => setDrawerOpen(false)}
      />
    </div>
  );
};

export default ExplainPage;
